# Generated by Django 4.1.7 on 2023-03-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorant',
            name='sexe',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
