# Generated by Django 4.1.7 on 2023-03-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_pv_lien_pv_cs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pv',
            old_name='cs',
            new_name='fichier',
        ),
        migrations.AddField(
            model_name='encadrant',
            name='laboratoire',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
