# Generated by Django 4.1.7 on 2023-03-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_doctorant_premiere_annee_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorant',
            name='date_EFST',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='premiere_annee_inscription',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
