# Generated by Django 4.1.7 on 2023-04-20 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_doctorant_date_efst'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorant',
            old_name='statut',
            new_name='status',
        ),
    ]
