# Generated by Django 4.1.7 on 2023-04-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_rename_statut_doctorant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorant',
            name='status',
            field=models.CharField(choices=[('Inscrit', 'Inscrit'), ('A soutenue', 'A soutenue'), ('Différé', 'Différé'), ('Radié', 'Radié')], max_length=50, null=True),
        ),
    ]
