# Generated by Django 4.1.7 on 2023-03-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_séminaire_résumé'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pv',
            name='lien',
        ),
        migrations.AddField(
            model_name='pv',
            name='cs',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
