# Generated by Django 4.1.7 on 2023-04-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_doctorant_date_efst'),
    ]

    operations = [
        migrations.AddField(
            model_name='pv',
            name='ordre_du_jour',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='option',
            field=models.CharField(choices=[('SIQ', 'SIQ'), ('SI', 'SI')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='statut',
            field=models.CharField(choices=[('Inscrit', 'Inscrit'), ('A soutenue', 'A soutenue'), ('Abondant', 'Abondant')], max_length=50, null=True),
        ),
    ]
