# Generated by Django 4.2 on 2023-05-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_doctorant_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorant',
            name='option',
            field=models.CharField(choices=[('SIQ', 'SIQ'), ('SI', 'SI')], max_length=100, null=True),
        ),
    ]
