# Generated by Django 4.2 on 2023-05-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_pv_année_alter_doctorant_co_directeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorant',
            name='option',
            field=models.CharField(choices=[('SI', 'SI'), ('SIQ', 'SIQ')], max_length=100, null=True),
        ),
    ]
